name: IGMA Designs
favicon: null
layout_spectrum: 0.7686658098828048
typography_spectrum: 0.8803918291814625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5141444499604404
  lightness: 0.9363708202727139
  saturation: 0.16905930591747165
  rhythmicContrast: 0.3505532629787922
purpose: []
